ur_arm:
  ip: 192.168.3.4
vive_tracker:
  left_serial: LHR-D78D8ACE
  right_serial: LHR-76281224
manus_glove:
  address: udp://127.0.0.1:9001
  left_id: 0
  right_id: 0
ruiyan_hand:
  port: can0
rgb_cameras: []
