# Hardware Configuration

ur_arm:
  ip: "192.168.1.5"

gello:
  port: "/dev/serial/by-id/usb-ROBOTIS_OpenRB-150_9321A3E850304A46462E3120FF0C1339-if00"
  # Windows example: "COM3"
  # Linux example: "/dev/ttyUSB0"

ruiyan_hand:
  port: "can0" # Default from RyHandDriver 
  init_script: "external/RuiyanHand_for_linux/ryhand_init.sh"

cameras:
  fingertips:
    thumb: 
      id: "usb-0000:00:14.0-5.1.2"
      offset: 0
    index: 
      id: "usb-0000:00:14.0-5.1.3"
      offset: 0
  realsense:
    - name: "rs_env"
      id: "usb-0000:00:14.0-5.2"
      offset: 4 # Resolves to video11
      zoom: 1.0
    - name: "rs_hand"
      id: "usb-0000:00:14.0-6"
      offset: 4 # Resolves to video18
      zoom: 1.0
