servo:
  speed: 0.5
  acceleration: 0.5
  dt: 0.0125
  lookahead_time: 0.1
  gain: 300
vive:
  translation_scale: 1.0
control:
  update_rate: 80.0
  input_timeout: 0.25
  hand_motor_speed: 1000
safety:
  max_linear_speed: 0.2
  max_angular_speed: 0.8
  max_translation_from_reference: 0.3
  max_rotation_from_reference: 1.0472
  max_tracker_translation_jump: 0.05
  max_tracker_rotation_jump: 0.35
