# @package _global_
defaults:
  - /workspace/train_diffusion_unet_ssr_pickplace_earbud_workspace
  - _self_

task:
  dataset:
    dataset_path: data/pickplace_earbud/place/ryhand_place_earbud.zarr

training:
  device: "cuda:0"

deployment:
  checkpoint_path: data/outputs/2026.04.02/14.39.04_train_diffusion_unet_hybrid_earbud_ssr_pickplace_earbud_image/checkpoints/latest.ckpt
  device: ${training.device}
  frequency: 15.0
  steps_per_inference: 4
  max_duration: 35.0
  dry_run: false
  no_start_pose: false